### ISSUE TITLE
Nozzle - Incorrect height

### ISSUE THREAD

**Issue by testbughub** [Kragrathea/OctoPrint-PrettyGCode#121]
Hi!

I just installed the plugin and started a print, when I noticed that the nozzle is going around at the wrong height:  
![nozzle](https://user-images.githubusercontent.com/30836300/130351254-cc36c887-30d2-4c7d-8b3d-c312c02ef3a9.png)

I looked around all the issues, but I couldn't find anything on this problem, altough I found #100,  
but I'm not sure if it's related (I have Arc Welder installed as well).

If I just missed some information, I apologize.

**Comment by Kragrathea** [comment]
When you first refresh a page it can take a minute or so to update the nozzle to the correct height. This is due to the way the octoprint sends gcode to the printer. I can only tell the Z height when the layer changes. If you wait does the nozzle eventual start using the correct height?

**Comment by testbughub** [comment]
Yep, you were right. I gave it a couple of minutes and it started working fine.
Thanks for the quick reply, and the plugin, of course!
