### ISSUE TITLE
Nozzle always at Z level 0

### ISSUE THREAD

**Issue by Xolverr** [Kragrathea/OctoPrint-PrettyGCode#140]
Screenshot from iPhone XR Chrome, but also occurs on PC and Mac Chrome. Not a terrible issue just not pretty 😂
![image](https://user-images.githubusercontent.com/98428552/180876459-60fc3b8b-2823-4dc8-a0dc-03b951e4ab80.jpeg)

**Comment by Kragrathea** [comment]
Not sure what would cause that. And I haven't had any other reports of this. Maybe something about the slicer you are using?

**Comment by Xolverr** [comment]
I use Cura. Most of the time after a little while it does fix itself, so it might have something to do with an unstable http connection. (I was using mobile data in the screenshot)

**Comment by Kragrathea** [comment]
Oh, There is a known issue where the Z height is only updated when the layer changes. This is because the Gcode leaves out the Z part until it changes. I seem to remember it was tricky to fix that bug for some reason...

**Comment by Xolverr** [comment]
Awesome, that sounds like its probably the problem, the model I was printing at that time was decently large. Thanks!
