### ISSUE TITLE
[Question]: Possible to create an image?

### ISSUE THREAD

**Issue by OllisGit** [Kragrathea/OctoPrint-PrettyGCode#20]
Hi @Kragrathea ,
first: Great work!!!

Do you think it possible to create an single image of a fully rendered gcode and store the file on the raspberry?

I looked into https://github.com/shodushi/gcode2png but I have a problem installing ```tvtk```.

Or do you know any python-lib that can create (nice looking, not line based) images from code?
 
Thx, in advance
Olli

**Comment by Kragrathea** [comment]
Probably. But not with this code, since its all web browser based.
