### ISSUE TITLE
Update Loop

### ISSUE THREAD

**Issue by jneilliii** [Kragrathea/OctoPrint-PrettyGCode#26]
You released version v1.0, but the setup.py is still loading v0.3 so results in an update loop. You need to update the line [here](https://github.com/Kragrathea/OctoPrint-PrettyGCode/blob/fdb63153843910037acfba3e0e3c85244250e53b/setup.py#L17) to be `1.0` as well.

**Comment by fernandex00** [comment]
Same here

**Comment by PatrickSp** [comment]
Same here

**Comment by MimbaMonkeyHouse** [comment]
Yup, here too. Do we need to uninstall the old version and reinstall the new version?
Anyone found a solution?

**Comment by fernandex00** [comment]
You need to unzip the file, edit the line mentioned in the first comment, create the zip file again, and update the add-on, it should work

**Comment by Kragrathea** [comment]
Ok, I think I fixed the issue. Let me know if not.

**Comment by jneilliii** [comment]
It did, thanks.

**Comment by gilshahar7** [comment]
Hey, im sorry for commenting on a closed issue but i am a complete noob, i cant find PrettyGCode in the plugin manager using the OctoPrint interface.. am i missing something?

**Comment by jneilliii** [comment]
It's not registered yet in the plugin repository.
