### ISSUE TITLE
GCode generated with PrusaSlicer doesnt render properly

### ISSUE THREAD

**Issue by Tirpitz93** [Kragrathea/OctoPrint-PrettyGCode#28]
I saw this was mentioned on the octoprint forums already.
Are there any Tweaks to slicer we can make to make it compatible, such as custom GCode?
![image](https://user-images.githubusercontent.com/6187560/81672812-9cf0ca80-9442-11ea-9286-40ec20d80aba.png)

**Comment by Kragrathea** [comment]
I think with the PrusaSlicer you have to turn on Verbose GCode in the options somewhere. I don't use that slicer myself...

**Comment by Tirpitz93** [comment]
> I think with the PrusaSlicer you have to turn on Verbose GCode in the options somewhere. I don't use that slicer myself...

I will try that now
