### ISSUE TITLE
Text Color for filename, layers, height, etc lost in background on full screen

### ISSUE THREAD

**Issue by msteele999** [Kragrathea/OctoPrint-PrettyGCode#31]
When I run PrettyGCode in full screen, some dashboard elements are not visible as they are the same color or near the same color as the the background (please see screen shot).

The plugin is absolutely phenomenal and I run all my jobs in this view.

![Screenshot_060120_034828_PM](https://user-images.githubusercontent.com/6474337/83448243-a2c54480-a41f-11ea-8713-3a0ed4727f74.jpg)

**Comment by msteele999** [comment]
![Screenshot_060120_035243_PM](https://user-images.githubusercontent.com/6474337/83448430-f2a40b80-a41f-11ea-9de9-ea6f120fb121.jpg)

**Comment by Kragrathea** [comment]
Others have reported issues with unreadable text and I am trying to figure out a solution.

**Comment by Kragrathea** [comment]
This should be fixed in the next release.
