### ISSUE TITLE
PiCam interference

### ISSUE THREAD

**Issue by FHOGPHIL** [Kragrathea/OctoPrint-PrettyGCode#33]
Installed today and PiCam stopped working  unistalled and it is back

**Comment by linuxgurugamer** [comment]
I have PiCAM installed as well, it didn't affect it when I installed.  I have both this and PiCAM working nicely together

**Comment by FHOGPHIL** [comment]
Have Octolapse running too. Maybe the three create conflict? 

Please excuse brevity and auto corrects - sent from iPhone!

**Comment by linuxgurugamer** [comment]
Octolapse, is that the time-lapse module?  If so, I also had that running.

I have a new install (1 week old), Pi-4, with Octoprint installed, a PiCam v2.  all three worked for me.
What else do you have installed?

**Comment by FHOGPHIL** [comment]
Same setup. All with most current updates. 
Did multiple restarts just to confirm. Checked all cables. When could get the video, uninstalled this and everything worked again. 

Please excuse brevity and auto corrects - sent from iPhone!

**Comment by Kragrathea** [comment]
Yikes. I don't have a PiCam so I can't check that out. Can you let me know if you are able to narrow it down?

**Comment by Kragrathea** [comment]
Did you ever figure this out? I am going to close until there is new info.
