### ISSUE TITLE
Feature Request - Themes / Switch GCode Visualizer and Camera

### ISSUE THREAD

**Issue by DylanCDuke** [Kragrathea/OctoPrint-PrettyGCode#36]
Great plugin, good work.

Looking to see if custom themes can be chosen. Looks like it utilizes themes from Themeify. Using discord theme+dashboard plugin, the text is unreadable on the white background.

Curious if this can be set independently to use the default on the plugin, while discord on my octoprint. 

Additionally, would be interesting to switch GCode and Camera, if I'm more interested in the camera view being prominent.

**Comment by DylanCDuke** [comment]
Maybe this plugin should just disregard theme? Dashboard has a setting to disregard in fullscreen, if that can be utilized that could fix this issue.

**Comment by Kragrathea** [comment]
I don't specifically use Themeify (unless that is what Octoprint uses) so I am not exactly sure what you are asking. You can probably fix the issue with text being unreadable by using the Addtional CSS section on the PrettyGCode tab. What text is unreadable?

**Comment by DylanCDuke** [comment]
Hey @Kragrathea - see example here:
https://gyazo.com/340f7d3b2ae63cce1bc8ecad7a2be251
Basically it's using Octoprint theme. So if I set this to default, text is no problem. But if I'm using themify and set to discorded theme, it changes those values on prettygcode plugin.

Honestly it could probably be fixed with custom CSS, I just don't know much CSS

**Comment by derekslenk** [comment]
If you figure out the CSS let me know. I am also missing the text

**Comment by DylanCDuke** [comment]
Yeah I played around with it a bit and couldn't ever get it to work @derekslenk 

@Kragrathea - might be able to provide fields for a couple elements on the dashboard the users that aren't familiar with CSS like us can just fill in with hex values or something? Just overwrites the default/theme

**Comment by Kragrathea** [comment]
The text not being visible in Themes will be fixed in the next release (1.2.1)

**Comment by DylanCDuke** [comment]
Thanks Kragrathea! I'll look for this release, and let you know if it's resolved on my end!

**Comment by Kragrathea** [comment]
I am going to close this. If it isn't actually fixed file a new issue.

**Comment by derekslenk** [comment]
Thank you @Kragrathea !
