### ISSUE TITLE
Feature Request - Rotate on Model

### ISSUE THREAD

**Issue by DylanCDuke** [Kragrathea/OctoPrint-PrettyGCode#37]
Sometimes I print models not in the middle of the build plate. A rotate on model, or center on model (similar to built in gcode viewer) would be helpful

**Comment by Kragrathea** [comment]
I tried auto centering the view at one point and it caused other issues. The solution I use is to use the mouse to drag the view to where you want the rotation centered. Then it will auto rotate around that point.
