### ISSUE TITLE
Feature request: Recenter model

### ISSUE THREAD

**Issue by KenLucke** [Kragrathea/OctoPrint-PrettyGCode#39]
I accidentally did a two finger swipe while over the visualizer, and the build plate and model went zooming off somewhere into the nether regions of the space-time continuum (I presume that Eddie's there, too*).  No way to find where it was and return it into the view.  I had to reload (not reboot) the OP instance to get it to return to the default.

A "maintain maximum size view"option would be nice, too, that would constantly make sure that the entire model is zoomed in as close as possible.

[*Obligatory HHGTTG reference.]

**Comment by Kragrathea** [comment]
I'd like to keep buttons and options to a minimum for simplicity sake. I might add a "reload gcode" button that would also recenter the view, but it wouldn't be that much different from just refreshing the page.
