### ISSUE TITLE
Bug:  Layer thermometer does not match current layer in Sync to Progress mode

### ISSUE THREAD

**Issue by KenLucke** [Kragrathea/OctoPrint-PrettyGCode#40]
If Sync To Progress mode is on, the layer thermometer on the right does not follow the progress of layers.  It should a) follow what layer the display is currently showing, and b) if dragged by the user, turn off SyncToProgress until manually reenabled.

**Comment by Kragrathea** [comment]
Tried to fix this and ran into a limitation of the slider library I am using. Not going to be able to fix right now.
