### ISSUE TITLE
Fat lines performance

### ISSUE THREAD

**Issue by sr1329** [Kragrathea/OctoPrint-PrettyGCode#45]
In either Firefox or Edge (latest) using "Fat Lines" looks amazing but these browsers cant handle it; I have a decent 8650u CPU 16GB RAM, and Intel integrated graphics. Is there some setting I should find on the browser?

**Comment by Kragrathea** [comment]
You could try Chrome to see if it is any better. If not the issue is probably the Intel graphics. The fat lines are unfortunately rather GPU intensive.

**Comment by sr1329** [comment]
Thank you. So it is fine for "sync to model" only when scrolling layers does it slow down.

**Comment by sr1329** [comment]
Yes indeed GPU shows 100% use. I'll connect to my 2080ti eGPU and I bet it will fly.
