### ISSUE TITLE
Feature Request: Option to switch right click and left click

### ISSUE THREAD

**Issue by mneumark** [Kragrathea/OctoPrint-PrettyGCode#47]
I switch back and forth between PrusaSlicer and Octoprint. In PrusaSlicer, click and dragging triggers orbiting. Right click and dragging triggers panning. In this plugin its the exact opposite. It would be nice to have the ability to flip it because I keep mixing it up when switching between them.

**Comment by Kragrathea** [comment]
I feel you! I have at least 5 different schemes that I have to deal with. And that is part of the problem. I can't support every possible combination. The library I am using only supports one at a time. And I don't really have the time to build out a UI to make it user configurable. Sorry. I really wish this had been standardized a long long time ago.
