### ISSUE TITLE
[Feature Request] Dedicated Link without acces to Octoprint UI

### ISSUE THREAD

**Issue by wuast94** [Kragrathea/OctoPrint-PrettyGCode#48]
Would be nice to have a dedicated Link that i can Share.
I do this for webcam with my reverse proxy, so all connections over a specific domain (printcam.domain.tld) is redirectet internally to the webcam url: 
http(s)://ip:port/webcam/?action=stream&1597856926977

The Important Thing is that no one can manipulate the url to get to the Octoprint webui. 

So if i had a dedicated Link that only Shows the 3d Model, Print Stats (Temp etc) and a Webcam without any navbar or something like that i could share it to my Friends without problems.

**Comment by Kragrathea** [comment]
The way it is currently to even view the link (even one without the UI elements) you would still have to let them log into the OP web interface. I think to do what you want you would need a new service running under the PI or OP and that is way outside what this plugin does, which is just a pretty front end on the Octoprint UI.
