### ISSUE TITLE
Possibility to add API / Render the whole thing in different program (OctoDash)

### ISSUE THREAD

**Issue by UnchartedBull** [Kragrathea/OctoPrint-PrettyGCode#50]
Hi there,

Your GCode viewer definitely is one of the best looking out there! I was just curious whether there was an option to extract the image / data to display or render the whole thing in another application? I know this is asking quiet a lot but I've been looking for quite some time now and haven't found anything as good looking as your renderer. 

Just to give you an idea what I thought about (I don't know whether that is possible / you would like something like that):
- Your plugin sends the preprocessed data (or even raw data) to OctoDash
- OctoDash would then use a part of your plugin to display the render in the user interface (ideally kind of realtime)

You would naturally receive full credit!

Let me know if you think this is possible / you'd like to pursue this idea and if so at which scope. Thanks :)

**Comment by Kragrathea** [comment]
Sorry, that would be a lot more work than I want to put into it.
