### ISSUE TITLE
Wrong rendering of G2 and G3 gcodes

### ISSUE THREAD

**Issue by sameSEA** [Kragrathea/OctoPrint-PrettyGCode#52]
With G2 and G3 moves picture gets corrupted. 
E.g. G code  processed with ArcWelder in Octoprint:
![PrettyGcode_G2_G3_errors](https://user-images.githubusercontent.com/34823161/90849965-8fe74f80-e33e-11ea-8cd3-77b36052ac6b.jpg)

**Comment by TodWulff** [comment]
Just stopped by to see if someone else had posted this as an issue, as I too am having issues with incorrect depiction by Pretty GCode, of Arc Welder plugin generated g-code (namely G2/G3).  https://i.imgur.com/EoJeRXu.png  If there is anything we can do to help, given you lack a machine that is compatible with these GCodes, I am sure that one of us would be willing to be a bit of a guinea pig.  I hang out at the OctoPrint Discord Server (@PhucKnutt).  Take care.

**Comment by ChristopheTdn** [comment]
I add the Arc welder octoprint page. Maybe the explanations can help you.
https://plugins.octoprint.org/plugins/arc_welder/?fbclid=IwAR3JfMrBeRPFaIDxuDC638kTmVe0Y0pCb44HKjgvEtWBooRj-c9WOBMtiI4
Thx for your work !

**Comment by Shama71** [comment]
Hi.
Please fix problem.
T
![Screenshot 2020-10-25 170520](https://user-images.githubusercontent.com/53084859/97105362-4ae7ec80-16e4-11eb-9fbd-1735db02c2f6.png)

![Screenshot 2020-10-25 170330](https://user-images.githubusercontent.com/53084859/97105322-0d835f00-16e4-11eb-9d19-0f79a679c280.png)

**Comment by Deses** [comment]
Like the other peeps, I also just installed the newly released ArcWelder and I'm also having this issue.

I'm printing a cylindrical object much like @Shama71 and only the supports or straight lines are visible.

I'm using Marlin 2.0.7.2 with a SKR board on an Ender 3 and arc support is enabled and working ok.

**Comment by NameOfTheDragon** [comment]
This suddenly became a lot more important with the release of the Arc Welder plugin. Here's my example:
![image](https://user-images.githubusercontent.com/1268490/97217180-c918c180-17be-11eb-8969-4f23b5ad800a.png)

FYI, I'm using Klipper firmware on an Ender-3, Klipper supports only the offset (X Y I J) version of the commands and doesn't support the R version. Luckily Arc Welder produces the version that works with Klipper. I've attached teh gcode file that I download from Octoprint after it was processed by Arc Welder.
[Roller_Blind_End_Clip_0.4n_0.2mm_PLA_ENDER3_49m.zip](https://github.com/Kragrathea/OctoPrint-PrettyGCode/files/5440886/Roller_Blind_End_Clip_0.4n_0.2mm_PLA_ENDER3_49m.zip)

**Comment by LMS0815** [comment]
> This is going to be a tough one. There are 2 version of each command with various different behaviors. And my printer doesn't support those commands either. I'll have to come back to this issue.

And yo need to check/evaluate the Firmware G90/G91 behavior (See OctoPrint [G90/G91](https://github.com/FormerLurker/ArcWelderPlugin/issues/38) flag).

**Comment by mriscoc** [comment]
I have the same problem, model is printed ok, but Gcode visualizer is wrong.
![1](https://user-images.githubusercontent.com/2745567/98458365-c1153600-215d-11eb-8fa2-c25a29ca1bcf.jpg)
![optimized](https://user-images.githubusercontent.com/2745567/98458367-c4102680-215d-11eb-8bf5-d5990d20b7f8.jpg)
![original](https://user-images.githubusercontent.com/2745567/98458373-cffbe880-215d-11eb-9906-8429608798e6.jpg)

**Comment by FormerLurker** [comment]
@Kragrathea, I'd like to help if I can.  Might be able to get arc commands working on your printer too if you give me some info about the make/model and a link to the current firmware.  Even if there are memory issues it might be possible to squeeze out enough to enable arcs.

Oh, nice plugin too!  Sorry I created issues for you :(

**Comment by Kragrathea** [comment]
I started on support for this. But I can't use it with my printer due to the fact I don't have enough firmware memory. I have a CR10 and I added a ABL that required me to disable ARC to fit.

**Comment by Kragrathea** [comment]
If you want to help implement these GCodes look in PrettyGCode.js for the G2 and G3 cases. And figure out how to make lineSegments out of the arc.

**Comment by FormerLurker** [comment]
@Kragrathea, I have already created code to deconstruct arcs into segments, and will take a look to see if it can be applied.  I've got 0 experience with 3d rendering, and haven't examined the code yet, so I can''t promise anything.

**Comment by FormerLurker** [comment]
Hmm.. it's a start, lol:

![image](https://user-images.githubusercontent.com/33363128/101260160-7acadc80-36f3-11eb-9f67-36709e837ba4.png)

Looks rough, but it's actually really close.  Will debug and get back to you.

**Comment by FormerLurker** [comment]
Getting closer:

![image](https://user-images.githubusercontent.com/33363128/101262274-026c1780-3703-11eb-8efa-3d30792ffcc2.png)

Need to tweak the arc interpolation settings, then I think it should be ready for more testing.  The pic here shows what old marlin with mm_per_arc_setting=1.0 would do (not pretty).  I have added some additional parameters.

Note:  I have not yet implemented the R format, but that won't be too bad.

**Comment by FormerLurker** [comment]
Ok, it is looking good now.  I have the beginnings of supporting the R parameter, but until I get some gcode that works it is just commented out with notes.  Here is the obligatory benchy :)

![image](https://user-images.githubusercontent.com/33363128/101265519-c63db480-370c-11eb-822c-22908554fae7.png)

**Comment by Kragrathea** [comment]
Fixed in latest version.
