### ISSUE TITLE
Strange view in Full Screen Mode (different browsers) (Dashboard/Status)

### ISSUE THREAD

**Issue by energiebrand** [Kragrathea/OctoPrint-PrettyGCode#53]
It seems that the PlugIn interferes with STATUS and Dashboard in all my different browsers (Chrome, Firefox, EDGE). In normal mode everything seems to be OK.
First one is FIREFOX 
WINDOWS 10

[Temp_tower.gcode.txt](https://github.com/Kragrathea/OctoPrint-PrettyGCode/files/5109338/Temp_tower.gcode.txt)

![Firefox-Poblem-1](https://user-images.githubusercontent.com/60507600/90901047-9f13df00-e3ca-11ea-80aa-0b26ebc0abfc.jpg)

[octoprint.log](https://github.com/Kragrathea/OctoPrint-PrettyGCode/files/5109325/octoprint.log)

![Versions](https://user-images.githubusercontent.com/60507600/90901058-a20ecf80-e3ca-11ea-9f23-d7c79b9519d1.jpg)

![Chrome_Poblem-1](https://user-images.githubusercontent.com/60507600/90901059-a20ecf80-e3ca-11ea-893b-d9f7e50e29f5.jpg)

![EDGE_Poblem-1](https://user-images.githubusercontent.com/60507600/90901065-a3d89300-e3ca-11ea-8df1-bbf3d9ff8d65.jpg)

**Comment by Kragrathea** [comment]
Changing the Zoom is not really a Browser setting. Its a per page configuration. Most browsers even have it mapped to the mouse wheel when you hold down Ctrl.
