### ISSUE TITLE
Width of line relative to screen not zoom level

### ISSUE THREAD

**Issue by vannaka** [Kragrathea/OctoPrint-PrettyGCode#56]
The width of the lines when the fatLines option is on is always the same. If I'm zoomed far in or out the width of the lines in pixels will be the same. What should happen is the width of the lines should be relative to the zoom level. I'm going to assume this is an issue because this extension would have to analyze the g-code in order to determine the width of the extrusion in real life. I think a good workaround would be to set the width based on the zoom level and just pick a good value that works ok-ish across most parts. Or a slider could even be added to control the line width.

**Comment by Kragrathea** [comment]
The main problem is I would have to reload the GCode and regenerate the model every time line width changes. If I remember right I think I picked a line size that looked about the same size as a standard nozzle width at the default zoom level.
