### ISSUE TITLE
Feature Request: Sync Layer Without Animation

### ISSUE THREAD

**Issue by 11chrisadams11** [Kragrathea/OctoPrint-PrettyGCode#57]
I think it would be nice to have an option to sync the layer progress without having the nozzle animation. On a layer change it would show the current full layer, basically like not syncing to progress and manually moving the slider.

I don't need to see the animation of what is happening, but it's nice to know what the layer is going to look like.

Thanks

**Comment by Kragrathea** [comment]
I don't want to add the complexity of another option. But I plan to do something to highlight the current layer at some point and that may be more or less the same thing you want.

**Comment by Kragrathea** [comment]
I added an option to disable the nozzle in version 1.2.2. That should be closer to what you want.

**Comment by 11chrisadams11** [comment]
Yes, that sound like it should work great. Thank you.
