### ISSUE TITLE
Feature Request: Display current layer number

### ISSUE THREAD

**Issue by will-stevenson** [Kragrathea/OctoPrint-PrettyGCode#58]
It would be nice to have an overlay with some info about the print job, primarily current layer # being printed.

**Comment by Kragrathea** [comment]
I might sync the slider to progress and possibly show current layer there. But my feeling is displaying the layer (and all other status) is really the job of the existing UI via the Status panel or by the Dashboard plugin.

**Comment by Kragrathea** [comment]
I added a layer number to the slider in next release (1.2.2)

**Comment by will-stevenson** [comment]
that’s amazing. thanks for the great work!

Will
________________________________
