### ISSUE TITLE
Using Backup/Restore  in Octoprint for some reason doesn't Backup/Restore PrettyGCode

### ISSUE THREAD

**Issue by LarryVand** [Kragrathea/OctoPrint-PrettyGCode#60]
Use the backup/restore function of Octoprint V1.4.2.
I selected the option to exclude uploaded files & metadata from the backup, and I also selected exclude timelapses from the backup.
I then formated a brand new SD card, loaded octopi 0.17.0, updated octoprint to V1.4.2 and tried the Backup/Restore function.
Every plugin that I had before loaded just fine. All except PrettyGCode. And could very well be that the backup function never backed up PrettyGCode in the first place. Either way PrettyGCode was the only plugin out of 11 that did not restore.

**Comment by Kragrathea** [comment]
Sorry, no idea on this one. And it would be a pain to reproduce. Unless someone can point out what I am doing wrong I am not going to try to fix right now.

**Comment by Kragrathea** [comment]
This turned out to be a bug in the plugin repository, and It should be fixed soon.

**Comment by LarryVand** [comment]
> This turned out to be a bug in the plugin repository, and It should be fixed soon.

That's great! Thanks for following up...
