### ISSUE TITLE
Camera window sizing

### ISSUE THREAD

**Issue by heaio9v2** [Kragrathea/OctoPrint-PrettyGCode#61]
It appears that a camera with a higher resolution than 640x480 will take up nearly the entire screen when enabled. 

![2020-08-29_11-44-00](https://user-images.githubusercontent.com/70445515/91641940-1231dc80-e9ed-11ea-8b57-9de013ae1dce.jpg)

**Comment by Kragrathea** [comment]
There is a "Additional CSS" section in the PrettyGCode tab where you can adjust this by adding some CSS to the page. The example CSS specifically resizes the camera window for this case.

**Comment by heaio9v2** [comment]
Missed the information at the bottom of the tab as I was looking for additional configuration options in the OctoPrint settings menu. No issue.
