### ISSUE TITLE
Does not allow printing with virtual printer

### ISSUE THREAD

**Issue by sr1329** [Kragrathea/OctoPrint-PrettyGCode#64]
When I try to print with virtual printer prettyGcode does not sync. Regular Gcode viewer does not start either. Terminal does not refresh. Disabling prettyGcode reenables printing fucntionality and regular gcode viewer and refresh of the terminal.

**Comment by Kragrathea** [comment]
Sorry, I don't have any idea. I use the virtual printer all the time for testing and it works correctly.

**Comment by sr1329** [comment]
Hi sorry you are right. It’s probably some other plugin. I’ll have to troubleshoot it more.

On Sep 6, 2020, at 3:43 PM, Kragrathea <notifications@github.com> wrote:

﻿

Sorry, I don't have any idea. I use the virtual printer all the time for testing and it works correctly.
