### ISSUE TITLE
Nozzle Visualization does not reflect Nozzle Size

### ISSUE THREAD

**Issue by raiscan** [Kragrathea/OctoPrint-PrettyGCode#65]
Hello!

The nozzle size ("0.4mm") displayed on the side of the nozzle is presumably static, but this information can be retrieved from the printer profile's extruder settings.

I appreciate this is potentially a high-effort, low-effect issue to fix but it's been something that's been bugging me :)

Thank you for your hard work on such a fantastic plugin!

**Comment by Kragrathea** [comment]
Those numbers are part of the 3d model of a nozzle I got somewhere. It would be too much work to generate them at runtime. Sorry.
