### ISSUE TITLE
Camera view does not respect OctoPrint webcam rotation setting

### ISSUE THREAD

**Issue by kodek** [Kragrathea/OctoPrint-PrettyGCode#66]
I just mounted my RasPi camera, and the mount required me to put the camera in a portrait orientation. I corrected this by enabling the OctoPi "Rotate webcam 90 degrees counter clockwise" option.

Unfortunately, the camera view in the PrettyGCode plugin continues to show a landscape view. Refreshing didn't help.

**Comment by Kragrathea** [comment]
All PrettyGCode does is visual relocate the web camera from the Octoprint Control Tab.  In my setup the camera is rotated and works correctly. If it is not displaying the same as that view then there must be something messed up in Octoprint or the CSS somewhere.

**Comment by Kragrathea** [comment]
I think this might be fixed in next release. I changed how the camera works. If not resubmit.
