### ISSUE TITLE
Camera shows up under "control" but not in "prettygcode" tab

### ISSUE THREAD

**Issue by slapjackios** [Kragrathea/OctoPrint-PrettyGCode#69]
As the title says, the camera shows up normally under the "control" tab (and when I press the Test button in webcam settings), but doesn't work when I have Pretty Gcode fullscreened.
It used to display nothing, but I tried messing with resizing it to 360x240 using CSS in the setting, but it only made this empty box appear.
Same thing happened before i added the Dashboard plugin (I didn't have it installed in the beginning).
![Capture](https://user-images.githubusercontent.com/71088560/93158478-dac56e80-f714-11ea-9edc-bdd7e792f220.JPG)
![Capture1](https://user-images.githubusercontent.com/71088560/93158481-dbf69b80-f714-11ea-90fd-491ef44505e5.JPG)
![Capture2](https://user-images.githubusercontent.com/71088560/93158482-dbf69b80-f714-11ea-8ade-96cf4b5ea21b.JPG)

edit: I forgot to mention that I don't use a camera over usb, but a stream over wifi using an app on an old phone of mine.

**Comment by Kragrathea** [comment]
Should be fixed in next release.
