### ISSUE TITLE
Gcode is not colored

### ISSUE THREAD

**Issue by RampedIndent** [Kragrathea/OctoPrint-PrettyGCode#70]
All the gcode i upload only shows up in orange, is there some option i need to select in my slicer or something?

![image](https://user-images.githubusercontent.com/39007301/93494046-ed77b780-f94f-11ea-8503-797aa4b9d946.png)

**Comment by Kragrathea** [comment]
You need to make sure that gcode comments are turned on in your slicer. PGC uses them to decide what color the lines should be.

**Comment by RampedIndent** [comment]
Thanks that fixed it, you should probably add something about that to the readme
