### ISSUE TITLE
Error detection

### ISSUE THREAD

**Issue by rnsi** [Kragrathea/OctoPrint-PrettyGCode#71]
Hi-

Love the plug-in. Wondering if it might be possible to compare the rendered image to the camera to detect a print failure. I know nothing about image analysis, but what do you think? I would think the camera would need to be mounted to the bed for a constant view. And there would need to be a setting to tell the plug-in where the camera is. Then the browser could sound an alarm if it detects spaghetti. Or just stop the print.

**Comment by Kragrathea** [comment]
Hmm. Might be possible, but it is beyond the scope of this plugin.
