### ISSUE TITLE
Issue with rendering

### ISSUE THREAD

**Issue by CaptainSweatpants** [Kragrathea/OctoPrint-PrettyGCode#78]
Noticed this started happening recently. The only change to my octoprint was adding ArcWelder plugin (not sure if that's causing this) but as you can see perimeter walls are not being rendered, travel lines are showing, and other top/bottom lines are either missing or out of wack. 

![Screenshot (21)](https://user-images.githubusercontent.com/65038502/97816711-0371db00-1c65-11eb-8611-a59dc7e40643.png)

**Comment by t413** [comment]
Same issue here. PrettyGCode doesn't support G2/G3 _arc move_ commands, just the standard G0/G1 linear moves. The built-in _GCode Viewer_ plugin supports arcs, interestingly. 

Took a look at the code but it's pretty terse javascripty javascript.. not my specialty.

**Comment by jpjokela** [comment]
![prettygcode-arc-fail](https://user-images.githubusercontent.com/10063279/98395975-ba0afc80-2065-11eb-87be-4a75dd97b1ff.png)
Yep, definitely Arc-Welder. Seems to draw lines between arc segments though (or something)

**Comment by NameOfTheDragon** [comment]
Duplicates Iss #52

**Comment by Kragrathea** [comment]
This is because arc is not supported yet. See issue #52
