### ISSUE TITLE
Rendering is shown only in tiny window in lower-left corner

### ISSUE THREAD

**Issue by timur-tabi** [Kragrathea/OctoPrint-PrettyGCode#95]
This is with Octoprint 1.5.2 running on a Mac with OS X 10.11.6

![Screen Shot 2020-12-20 at 2 55 02 PM](https://user-images.githubusercontent.com/1065860/102724194-86152f00-42d3-11eb-80b7-5dea8c577ec2.png)

**Comment by Kragrathea** [comment]
Does it render correctly in the tab mode?

**Comment by timur-tabi** [comment]
It does the same thing in tab mode.  Just a small rectangle in the lower-left.

**Comment by Kragrathea** [comment]
The only thing I can think of is a plugin conflict. What other ones do you have installed? Maybe try disabling them to see if can figure out if that is the problem.

**Comment by timur-tabi** [comment]
Looks like it's a browser bug.  It only happens on Firefox on one of my Macs.  With any other browser or any other computer (including other Macs), it works fine.  I even tried switching to safe mode, but that only made it worse (no image at all).
